# ./netlify.toml

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
publish = "/opt/build/repo/release/wwwroot" # Or your Jekyll output directory
command = ""      # Clear the build command