name: Deploy to GitHub Pages
on:
  push:
    branches: [master] 
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 3.1
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 7.0.102
      - name: publish .NET Core Project
        run: dotnet publish ADArCWebApp.csproj -c Release -o release --nologo
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
      - name: Add .nojekyll file
        run: touch release/.nojekyll
      - name: copy release/index.html to release/404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html
