name: Deploy to GitHub Pages
on:
  push:
    branches: [master]
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Publish .NET Core Project
        run: dotnet publish ADArCWebApp.csproj -c Release -o release --nologo
      
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      
      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html
      
      - name: Append cache-busting query strings
        run: |
          RANDOM_STR=$(date +%s%N)
          sed -i "s|\(src=\|href=\)\"\([^\"]*\)\"|\1\"\2?v=$RANDOM_STR\"|g" index.html
          sed -i "s|\(src=\|href=\)\"\([^\"]*\)\"|\1\"\2?v=$RANDOM_STR\"|g" 404.html

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
