name: Deploy to GitHub Pages
on:
  push:
    branches: [master]
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create redirect page
        run: |
          mkdir -p public
          cat > public/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Redirecting...</title>
            <meta http-equiv="refresh" content="0; url=https://your-new-site.com">
            <link rel="canonical" href="https://your-new-site.com">
          </head>
          <body>
            <p>Redirecting to <a href="https://your-new-site.com">https://your-new-site.com</a>...</p>
            <script>window.location.href = "https://your-new-site.com";</script>
          </body>
          </html>
          EOF
      
      - name: Commit to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCH: gh-pages
          FOLDER: public
